###User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name":"said",
    "company" : "Company name",
    "adress" : "some adress sydney",
    "phone" : "0645127896",
    "email" : "e@e.com",
    "password" : "secret123" 
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZS5jb20iLCJpYXQiOjE3Mjk4MDYxMDIsImV4cCI6MTcyOTgwNzAwMn0.G_h-Q_xSEbUyuZcHhrt072wuSmmbvG7TH5FDZ-WO8Zs


### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email" : "e@e.com",
    "password" : "secret123" 
}


//Access JWT :  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVAZS5jb20iLCJpYXQiOjE3Mjk2Mjg1NzAsImV4cCI6MTcyOTYyOTQ3MH0.DXwxg_n35wSSt0U3Fbv4eKtADTcm5qysioOK9d3g9y0